wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.0004537646917482162
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 61
ae_n_kernels_2:
  value: 68
cb_lr:
  value: 0.01903159644750832
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 64
est_d_hidden:
  value: 170
est_dropout:
  value: 0.2014849238740506
est_kernel_size_1:
  value: 6
est_kernel_size_2:
  value: 6
est_kernel_size_3:
  value: 7
est_kernel_size_4:
  value: 4
est_kernel_size_5:
  value: 5
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 4
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 208
est_n_kernels_1:
  value: 54
est_n_kernels_2:
  value: 62
est_n_kernels_3:
  value: 99
est_n_kernels_4:
  value: 67
est_n_kernels_5:
  value: 64
est_num_layers:
  value: 3
est_temperature:
  value: 33
