wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.027140615862124476
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 16
ae_n_kernels_2:
  value: 218
cb_lr:
  value: 0.019576066760406716
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 256
est_d_hidden:
  value: 251
est_dropout:
  value: 0.2310307418348502
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 6
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 7
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 4
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 69
est_n_kernels_1:
  value: 44
est_n_kernels_2:
  value: 55
est_n_kernels_3:
  value: 199
est_n_kernels_4:
  value: 76
est_n_kernels_5:
  value: 147
est_num_layers:
  value: 4
est_temperature:
  value: 30
