wandb_version: 1

ae_batch_size:
  value: 512
ae_kernel_size_1:
  value: 3
ae_kernel_size_2:
  value: 3
ae_lr:
  value: 0.0208859896126393
ae_maxpooling_1:
  value: 2
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 21
ae_n_kernels_2:
  value: 62
cb_lr:
  value: 0.00617803642091713
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 256
est_d_hidden:
  value: 56
est_dropout:
  value: 0.39724251114803544
est_kernel_size_1:
  value: 5
est_kernel_size_2:
  value: 5
est_kernel_size_3:
  value: 6
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 5
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 117
est_n_kernels_1:
  value: 59
est_n_kernels_2:
  value: 48
est_n_kernels_3:
  value: 100
est_n_kernels_4:
  value: 234
est_n_kernels_5:
  value: 243
est_num_layers:
  value: 3
est_pool_dim:
  value: time
est_temperature:
  value: 30
