wandb_version: 1

ae_batch_size:
  value: 512
ae_kernel_size_1:
  value: 3
ae_kernel_size_2:
  value: 3
ae_lr:
  value: 0.00012027328139688198
ae_maxpooling_1:
  value: 2
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 22
ae_n_kernels_2:
  value: 220
cb_lr:
  value: 0.02302655807301973
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 64
est_d_hidden:
  value: 179
est_dropout:
  value: 0.29912944735568214
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 6
est_kernel_size_4:
  value: 5
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 6
est_maxpooling_3:
  value: 5
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 246
est_n_kernels_1:
  value: 53
est_n_kernels_2:
  value: 32
est_n_kernels_3:
  value: 234
est_n_kernels_4:
  value: 123
est_n_kernels_5:
  value: 95
est_num_layers:
  value: 2
est_pool_dim:
  value: time
est_temperature:
  value: 32
