wandb_version: 1

ae_batch_size:
  value: 512
ae_kernel_size_1:
  value: 3
ae_kernel_size_2:
  value: 3
ae_lr:
  value: 0.0014282566907699837
ae_maxpooling_1:
  value: 2
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 185
cb_lr:
  value: 0.004181935618000145
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 512
est_d_hidden:
  value: 134
est_dropout:
  value: 0.25601310799163746
est_kernel_size_1:
  value: 7
est_kernel_size_2:
  value: 7
est_kernel_size_3:
  value: 7
est_kernel_size_4:
  value: 4
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 6
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 244
est_n_kernels_1:
  value: 41
est_n_kernels_2:
  value: 48
est_n_kernels_3:
  value: 162
est_n_kernels_4:
  value: 92
est_n_kernels_5:
  value: 114
est_num_layers:
  value: 2
est_pool_dim:
  value: time
est_temperature:
  value: 30
