wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0054780263445055434
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 51
ae_n_kernels_2:
  value: 204
cb_lr:
  value: 0.001234168320527831
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 128
est_d_hidden:
  value: 135
est_dropout:
  value: 0.23186867820691015
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 5
est_kernel_size_3:
  value: 7
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 5
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 6
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 235
est_n_kernels_1:
  value: 17
est_n_kernels_2:
  value: 54
est_n_kernels_3:
  value: 150
est_n_kernels_4:
  value: 202
est_n_kernels_5:
  value: 180
est_num_layers:
  value: 3
est_temperature:
  value: 30
