wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0027469741931758517
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 63
ae_n_kernels_2:
  value: 163
cb_lr:
  value: 0.010571566764566892
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 256
est_d_hidden:
  value: 200
est_dropout:
  value: 0.17777724139608478
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 5
est_maxpooling_1:
  value: 6
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 94
est_n_kernels_1:
  value: 21
est_n_kernels_2:
  value: 47
est_n_kernels_3:
  value: 193
est_n_kernels_4:
  value: 158
est_n_kernels_5:
  value: 249
est_num_layers:
  value: 5
est_temperature:
  value: 33
