wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.0001032128083043081
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 139
ae_n_kernels_1:
  value: 35
ae_n_kernels_2:
  value: 86
cb_lr:
  value: 0.0002070167316876511
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 148
est_batch_size:
  value: 128
est_d_hidden:
  value: 246
est_dropout:
  value: 0.3274808891616705
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 135
est_n_kernels_1:
  value: 31
est_n_kernels_2:
  value: 19
est_n_kernels_3:
  value: 73
est_num_layers:
  value: 3
est_temperature:
  value: 30
