wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0002078385931088427
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 52
ae_n_kernels_1:
  value: 35
ae_n_kernels_2:
  value: 169
cb_lr:
  value: 0.00010151075003209388
cb_momentum:
  value: 0.8
cb_n_epochs:
  value: 104
est_batch_size:
  value: 128
est_d_hidden:
  value: 155
est_dropout:
  value: 0.3688782892107382
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 227
est_n_kernels_1:
  value: 8
est_n_kernels_2:
  value: 54
est_n_kernels_3:
  value: 95
est_num_layers:
  value: 3
est_temperature:
  value: 32
