wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.0008713432317464789
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 212
cb_lr:
  value: 0.008010545361228619
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 127
est_dropout:
  value: 0.2959011059545895
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 5
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 157
est_n_kernels_1:
  value: 32
est_n_kernels_2:
  value: 39
est_n_kernels_3:
  value: 80
est_n_kernels_4:
  value: 111
est_n_kernels_5:
  value: 126
est_num_layers:
  value: 4
est_temperature:
  value: 30
