wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.003824490520088334
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 49
ae_n_kernels_2:
  value: 220
cb_lr:
  value: 0.0026044423653836133
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 208
est_dropout:
  value: 0.38147625562226894
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 62
est_n_kernels_1:
  value: 24
est_n_kernels_2:
  value: 39
est_n_kernels_3:
  value: 66
est_n_kernels_4:
  value: 68
est_n_kernels_5:
  value: 126
est_num_layers:
  value: 2
est_temperature:
  value: 31
