wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.031929318430136994
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 54
ae_n_kernels_2:
  value: 87
cb_lr:
  value: 0.03184105439589318
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 128
est_d_hidden:
  value: 227
est_dropout:
  value: 0.22674558453522345
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 91
est_n_kernels_1:
  value: 20
est_n_kernels_2:
  value: 51
est_n_kernels_3:
  value: 104
est_n_kernels_4:
  value: 93
est_n_kernels_5:
  value: 83
est_num_layers:
  value: 2
est_temperature:
  value: 31
