wandb_version: 1

method:
  desc: null
  value: bayes
metric:
  desc: null
  value:
    goal: minimize
    name: test_loss_avg
parameters:
  desc: null
  value:
    batch_size:
      values:
      - 64
    d_model:
      value: 23
    dff:
      values:
      - 128
      - 256
    dropout:
      distribution: uniform
      min: 0.05
      max: 0.15
    l_win:
      distribution: int_uniform
      min: 120
      max: 125
    lr:
      distribution: log_uniform
      min: -6.5
      max: -5.5
    n_epochs:
      distribution: int_uniform
      min: 60
      max: 100
    n_head:
      values:
      - 1
      - 23
    num_layers:
      distribution: int_uniform
      min: 1
      max: 3
    weight_decay:
      distribution: log_uniform
      min: -6
      max: -4
    num_workers:
      values:
      - 2
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710906084.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.10
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 64
d_model:
  desc: null
  value: 23
dff:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.09155869557935126
l_win:
  desc: null
  value: 124
lr:
  desc: null
  value: 0.002639276798512375
n_epochs:
  desc: null
  value: 76
n_head:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 3
num_workers:
  desc: null
  value: 2
weight_decay:
  desc: null
  value: 0.012958015126525068
