wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0014116010568459496
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 17
ae_n_kernels_2:
  value: 207
cb_lr:
  value: 0.04552340374049283
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 117
est_dropout:
  value: 0.36414737112061246
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 221
est_n_kernels_1:
  value: 29
est_n_kernels_2:
  value: 30
est_n_kernels_3:
  value: 111
est_n_kernels_4:
  value: 115
est_n_kernels_5:
  value: 123
est_num_layers:
  value: 1
est_temperature:
  value: 30
