wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0033627625689380165
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 39
ae_n_kernels_2:
  value: 41
cb_lr:
  value: 0.014407154840022664
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 171
est_dropout:
  value: 0.2088860475557705
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 72
est_n_kernels_1:
  value: 29
est_n_kernels_2:
  value: 56
est_n_kernels_3:
  value: 114
est_n_kernels_4:
  value: 93
est_n_kernels_5:
  value: 98
est_num_layers:
  value: 1
est_temperature:
  value: 32
