wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.028336082332863465
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 28
ae_n_kernels_2:
  value: 204
cb_lr:
  value: 0.013748623533796344
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 256
est_d_hidden:
  value: 126
est_dropout:
  value: 0.3138538505830212
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 46
est_n_kernels_1:
  value: 29
est_n_kernels_2:
  value: 25
est_n_kernels_3:
  value: 107
est_n_kernels_4:
  value: 107
est_n_kernels_5:
  value: 74
est_num_layers:
  value: 1
est_temperature:
  value: 30
