wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0014528890788918188
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 29
ae_n_kernels_2:
  value: 139
cb_lr:
  value: 0.005848458722116456
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 97
est_dropout:
  value: 0.2990790848817985
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 50
est_n_kernels_1:
  value: 9
est_n_kernels_2:
  value: 17
est_n_kernels_3:
  value: 77
est_n_kernels_4:
  value: 108
est_n_kernels_5:
  value: 79
est_num_layers:
  value: 2
est_temperature:
  value: 33
