wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.0008278130280159606
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 51
ae_n_kernels_2:
  value: 84
cb_lr:
  value: 0.013103848325226429
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 131
est_dropout:
  value: 0.34877442626305744
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 172
est_n_kernels_1:
  value: 26
est_n_kernels_2:
  value: 48
est_n_kernels_3:
  value: 96
est_n_kernels_4:
  value: 72
est_n_kernels_5:
  value: 78
est_num_layers:
  value: 2
est_temperature:
  value: 32
