wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0004608631186411616
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 256
cb_lr:
  value: 0.0046446149249489135
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 256
est_d_hidden:
  value: 246
est_dropout:
  value: 0.20516651974809255
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 120
est_n_kernels_1:
  value: 18
est_n_kernels_2:
  value: 48
est_n_kernels_3:
  value: 81
est_n_kernels_4:
  value: 69
est_n_kernels_5:
  value: 106
est_num_layers:
  value: 1
est_temperature:
  value: 31
