wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.012549702155697838
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 50
ae_n_kernels_2:
  value: 193
cb_lr:
  value: 0.0026467658078008615
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 128
est_d_hidden:
  value: 183
est_dropout:
  value: 0.3631115523049081
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 51
est_n_kernels_1:
  value: 24
est_n_kernels_2:
  value: 22
est_n_kernels_3:
  value: 120
est_n_kernels_4:
  value: 94
est_n_kernels_5:
  value: 96
est_num_layers:
  value: 2
est_temperature:
  value: 33
