wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.0033692765747165253
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 21
ae_n_kernels_2:
  value: 254
cb_lr:
  value: 0.0012784955448096014
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 191
est_dropout:
  value: 0.2203036965219616
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 136
est_n_kernels_1:
  value: 13
est_n_kernels_2:
  value: 16
est_n_kernels_3:
  value: 88
est_n_kernels_4:
  value: 71
est_n_kernels_5:
  value: 106
est_num_layers:
  value: 1
est_temperature:
  value: 30
