method: bayes
metric:
    goal: minimize
    name: estimator_val_loss #val_acc 

parameters:

#Denoiser configurations 
  ae_batch_size:
    values: [64,128,256,512]
  ae_n_epochs: 
    value: 3
    # distribution: int_uniform
    # min: 100
    # max: 150 
  ae_lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.05
  ae_momentum: #adam thi co weight decay 
    values: [0.5,0.6,0.7,0.8,0.9] #0.5-0.7 is beneficial for noisy datasets 
 
  # ae_kernel_size_1:
  #   distribution: int_uniform 
  #   min: 2
  #   max: 7
  # ae_kernel_size_2:
  #   distribution: int_uniform
  #   min: 2
  #   max: 7 
  # ae_kernel_size_1:
  #   value: 3

  # ae_kernel_size_2:
  #   value: 3

 
  # ae_maxpooling_1:
  #   value: 2
    # distribution: int_uniform 
    # min: 2
    # max: 5
  ae_maxpooling_2:
    values: [2,3]
    # distribution: int_uniform
    # min: 2
    # max: 6 

  ae_n_kernels_1:
    distribution: int_uniform 
    min: 16
    max: 64 
  ae_n_kernels_2:
    distribution: int_uniform
    min: 32
    max: 256

#Estimator configurations 
  est_batch_size:
    values: [64,128,256,512]

  # est_pool_dim:
  #   value: "time"

  est_dropout:
    distribution: uniform
    min: 0.1
    max: 0.4

  est_n_basis_kernels:
    distribution: int_uniform 
    min: 16
    max: 256

  est_kernel_size_1:
    distribution: int_uniform 
    min: 2
    max: 5
  est_kernel_size_2:
    distribution: int_uniform 
    min: 2
    max: 5
  est_kernel_size_3:
    distribution: int_uniform 
    min: 2
    max: 5 
  est_kernel_size_4:
    distribution: int_uniform 
    min: 2
    max: 5  
  est_kernel_size_5:
    distribution: int_uniform 
    min: 2
    max: 5  

  est_n_kernels_1:
    distribution: int_uniform 
    min: 8
    max: 32  
  est_n_kernels_2:
    distribution: int_uniform 
    min: 16
    max: 64 
  est_n_kernels_3:
    distribution: int_uniform 
    min: 64
    max: 128 
  est_n_kernels_4:
    distribution: int_uniform 
    min: 64
    max: 128 
  est_n_kernels_5:
    distribution: int_uniform 
    min: 64
    max: 128
  
  est_num_layers:
    values: [1,2,3,4,5]

  est_temperature:
    values: [30,31,32,33]
  
  est_maxpooling_1:
    distribution: int_uniform 
    min: 2
    max: 4
  
  est_maxpooling_2:
    distribution: int_uniform 
    min: 2
    max: 4
  
  est_maxpooling_3:
    distribution: int_uniform 
    min: 2
    max: 4

  est_maxpooling_4:
    distribution: int_uniform 
    min: 2
    max: 4

  est_maxpooling_5:
    distribution: int_uniform 
    min: 2
    max: 4
  
  est_d_hidden:
    distribution: int_uniform
    min: 32
    max: 256

  
  

      
  # Combined model configs
  cb_n_epochs:
    value: 100
    # distribution: int_uniform
    # min: 50
    # max: 150
  cb_lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.05
  cb_momentum:
      value: 0.9
  


      

