method: bayes
metric:
    goal: minimize
    name: estimator_loss #val_acc 

parameters:
#Estimator configurations 
  est_batch_size:
    values: [128,256,512]

  # est_pool_dim:
  #   value: "time"

  est_dropout:
    distribution: uniform
    min: 0.1
    max: 0.2

  est_n_basis_kernels:
    distribution: int_uniform 
    min: 16
    max: 256

  est_kernel_size_1:
    distribution: int_uniform 
    min: 2
    max: 5
  est_kernel_size_2:
    distribution: int_uniform 
    min: 2
    max: 5
  est_kernel_size_3:
    distribution: int_uniform 
    min: 2
    max: 3
  # est_kernel_size_4:
  #   distribution: int_uniform 
  #   min: 2
  #   max: 4  
  # est_kernel_size_5:
  #   distribution: int_uniform 
  #   min: 2
  #   max: 4  

  est_n_kernels_1:
    distribution: int_uniform 
    min: 8
    max: 32  
  est_n_kernels_2:
    distribution: int_uniform 
    min: 16
    max: 64 
  est_n_kernels_3:
    distribution: int_uniform 
    min: 64
    max: 128 
  # est_n_kernels_4:
  #   distribution: int_uniform 
  #   min: 64
  #   max: 128 
  # est_n_kernels_5:
  #   distribution: int_uniform 
  #   min: 64
  #   max: 128
  
  est_num_layers:
    values: [1,2,3]

  est_temperature:
    values: [30,31,32,33]
  
  est_maxpooling_1:
    values: [2,3]
  
  est_maxpooling_2:
    # distribution: int_uniform 
    values: [2,3]
  
  est_maxpooling_3:
    # distribution: int_uniform 
    values: [2,3]
  

  # est_maxpooling_4:
  #   distribution: int_uniform 
  #   min: 2
  #   max: 3

  # est_maxpooling_5:
  #   distribution: int_uniform 
  #   min: 2
  #   max: 3
  
  est_d_hidden:
    values: [32, 64, 128, 256] 
      
  # Combined model configs
  est_n_epochs:
    #  value: 1
    distribution: int_uniform
    min: 20
    max: 100
  est_lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.05
 
  


      

