ae_batch_size: 128
ae_kernel_size_1: 3
ae_kernel_size_2: 3
ae_lr: 0.000609411270877071
ae_maxpooling_1: 2
ae_maxpooling_2: 2
ae_momentum: 0.6
ae_n_epochs: 35
ae_n_kernels_1: 20
ae_n_kernels_2: 133
denoiser_loss: 0.0034804849688393567
est_batch_size: 64
est_d_hidden: 256
est_dropout: 0.18001145524855627
est_kernel_size_1: 3
est_kernel_size_2: 2
est_kernel_size_3: 2
est_lr: 0.00576754792610375
est_maxpooling_1: 2
est_maxpooling_2: 2
est_maxpooling_3: 2
est_momentum: 0.9
est_n_basis_kernels: 58
est_n_epochs: 68
est_n_kernels_1: 19
est_n_kernels_2: 17
est_n_kernels_3: 71
est_num_layers: 1
est_temperature: 32
estimator_loss: 0.20557034640358043
#




  #  ae_batch_size: 128
#   ae_n_epochs: 35
#   est_n_epochs: 68
#   ae_lr: 0.000609411270877071
   
#   ae_momentum: 0.6
 
#   ae_kernel_size_1: 3
#   ae_kernel_size_2: 3 

#   ae_maxpooling_1: 2
    
#   ae_maxpooling_2: 2

#   ae_n_kernels_1: 16
  
#   ae_n_kernels_2: 32
  



# #Estimator configurations 
#   est_batch_size: 256

#   # est_pool_dim:
#   #   value: "time"

#   est_dropout: 0.1

#   est_n_basis_kernels: 16
   

#   est_kernel_size_1: 3
#   est_kernel_size_2: 3 
#   est_kernel_size_3: 3
   
#   # est_kernel_size_4:
#   #   distribution: int_uniform 
#   #   min: 2
#   #   max: 4  
#   # est_kernel_size_5:
#   #   distribution: int_uniform 
#   #   min: 2
#   #   max: 4  

#   est_n_kernels_1: 8  
#   est_n_kernels_2: 16
#   est_n_kernels_3: 32
#   # est_n_kernels_4:
#   #   distribution: int_uniform 
#   #   min: 64
#   #   max: 128 
#   # est_n_kernels_5:
#   #   distribution: int_uniform 
#   #   min: 64
#   #   max: 128
  
#   est_num_layers: 3
 

#   est_temperature: 30
  
  
#   est_maxpooling_1: 2
  
#   est_maxpooling_2: 2
    
#   est_maxpooling_3: 2 
  
  

#   # est_maxpooling_4:
#   #   distribution: int_uniform 
#   #   min: 2
#   #   max: 3

#   # est_maxpooling_5:
#   #   distribution: int_uniform 
#   #   min: 2
#   #   max: 3
  
#   est_d_hidden: 256
  
      
#   # Combined model configs
#   est_n_epochs: 10
#   est_lr: 0.005

  


      

