wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.008887584807574924
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 18
ae_n_kernels_2:
  value: 146
est_batch_size:
  value: 64
est_d_hidden:
  value: 32
est_dropout:
  value: 0.1728365129748771
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_lr:
  value: 0.02237613394846696
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_momentum:
  value: 0.9
est_n_basis_kernels:
  value: 215
est_n_epochs:
  value: 1
est_n_kernels_1:
  value: 16
est_n_kernels_2:
  value: 16
est_n_kernels_3:
  value: 113
est_num_layers:
  value: 1
est_temperature:
  value: 31
