wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.00035079595096161636
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 113
ae_n_kernels_1:
  value: 32
ae_n_kernels_2:
  value: 235
cb_lr:
  value: 0.0011201087493236594
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 92
est_batch_size:
  value: 128
est_d_hidden:
  value: 70
est_dropout:
  value: 0.3720862248200394
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 91
est_n_kernels_1:
  value: 11
est_n_kernels_2:
  value: 35
est_n_kernels_3:
  value: 99
est_num_layers:
  value: 2
est_temperature:
  value: 30
