wandb_version: 1

ae_batch_size:
  value: 64
ae_kernel_size_1:
  value: 5
ae_kernel_size_2:
  value: 3
ae_lr:
  value: 0.01716304994440599
ae_maxpooling_1:
  value: 2
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 150
ae_n_kernels_1:
  value: 21
ae_n_kernels_2:
  value: 198
cb_lr:
  value: 0.004091803425548739
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 119
est_batch_size:
  value: 64
est_d_hidden:
  value: 152
est_dropout:
  value: 0.3711831963711863
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 6
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 6
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 6
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 6
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 131
est_n_kernels_1:
  value: 24
est_n_kernels_2:
  value: 52
est_n_kernels_3:
  value: 161
est_n_kernels_4:
  value: 162
est_n_kernels_5:
  value: 245
est_num_layers:
  value: 2
est_pool_dim:
  value: time
est_temperature:
  value:
  - 30
  - 31
  - 32
  - 33
