wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.00028050986800236223
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 27
ae_n_kernels_2:
  value: 41
cb_lr:
  value: 0.009105051986331276
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 181
est_dropout:
  value: 0.10488739796649574
est_kernel_size_1:
  value: 6
est_kernel_size_2:
  value: 6
est_kernel_size_3:
  value: 5
est_kernel_size_4:
  value: 6
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 5
est_maxpooling_2:
  value: 4
est_maxpooling_3:
  value: 5
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 6
est_n_basis_kernels:
  value: 26
est_n_kernels_1:
  value: 48
est_n_kernels_2:
  value: 64
est_n_kernels_3:
  value: 240
est_n_kernels_4:
  value: 250
est_n_kernels_5:
  value: 211
est_num_layers:
  value: 4
est_temperature:
  value: 31
