wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.01362367709777943
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 25
ae_n_kernels_2:
  value: 183
cb_lr:
  value: 0.001081202567585204
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 230
est_dropout:
  value: 0.17185503138799785
est_kernel_size_1:
  value: 6
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 7
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 248
est_n_kernels_1:
  value: 63
est_n_kernels_2:
  value: 45
est_n_kernels_3:
  value: 236
est_n_kernels_4:
  value: 115
est_n_kernels_5:
  value: 122
est_num_layers:
  value: 1
est_temperature:
  value: 33
