wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.004223583472968208
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 44
ae_n_kernels_2:
  value: 143
cb_lr:
  value: 0.0012819913490056166
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 38
est_dropout:
  value: 0.15114664903775177
est_kernel_size_1:
  value: 6
est_kernel_size_2:
  value: 5
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 41
est_n_kernels_1:
  value: 30
est_n_kernels_2:
  value: 19
est_n_kernels_3:
  value: 224
est_n_kernels_4:
  value: 215
est_n_kernels_5:
  value: 175
est_num_layers:
  value: 3
est_temperature:
  value: 31
