wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.015345082922801003
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 175
cb_lr:
  value: 0.0012856297024196725
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 202
est_dropout:
  value: 0.3648004296583437
est_kernel_size_1:
  value: 6
est_kernel_size_2:
  value: 6
est_kernel_size_3:
  value: 5
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 5
est_maxpooling_4:
  value: 4
est_maxpooling_5:
  value: 6
est_n_basis_kernels:
  value: 200
est_n_kernels_1:
  value: 57
est_n_kernels_2:
  value: 42
est_n_kernels_3:
  value: 101
est_n_kernels_4:
  value: 157
est_n_kernels_5:
  value: 216
est_num_layers:
  value: 4
est_temperature:
  value: 30
