wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0007561508242440907
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 87
ae_n_kernels_1:
  value: 20
ae_n_kernels_2:
  value: 90
cb_lr:
  value: 0.010747037497296347
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 78
est_batch_size:
  value: 512
est_d_hidden:
  value: 46
est_dropout:
  value: 0.3890143268412053
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_n_basis_kernels:
  value: 244
est_n_kernels_1:
  value: 23
est_n_kernels_2:
  value: 28
est_n_kernels_3:
  value: 93
est_num_layers:
  value: 1
est_temperature:
  value: 32
