wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0029241991823874274
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 129
ae_n_kernels_1:
  value: 62
ae_n_kernels_2:
  value: 55
cb_lr:
  value: 0.0032829422675387243
cb_momentum:
  value: 0.8
cb_n_epochs:
  value: 65
est_batch_size:
  value: 256
est_d_hidden:
  value: 172
est_dropout:
  value: 0.1570845114898635
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 2
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 133
est_n_kernels_1:
  value: 26
est_n_kernels_2:
  value: 42
est_n_kernels_3:
  value: 128
est_num_layers:
  value: 1
est_temperature:
  value: 31
