wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.00199219158648886
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 63
ae_n_kernels_2:
  value: 64
cb_lr:
  value: 0.0029919312555856596
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 256
est_d_hidden:
  value: 201
est_dropout:
  value: 0.16023457583728842
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 6
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 4
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 147
est_n_kernels_1:
  value: 63
est_n_kernels_2:
  value: 56
est_n_kernels_3:
  value: 220
est_n_kernels_4:
  value: 79
est_n_kernels_5:
  value: 97
est_num_layers:
  value: 5
est_temperature:
  value: 30
