wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.026908144359655047
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 74
cb_lr:
  value: 0.01187582730766979
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 512
est_d_hidden:
  value: 212
est_dropout:
  value: 0.119794551781077
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 7
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 5
est_kernel_size_5:
  value: 6
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 4
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 187
est_n_kernels_1:
  value: 54
est_n_kernels_2:
  value: 52
est_n_kernels_3:
  value: 166
est_n_kernels_4:
  value: 114
est_n_kernels_5:
  value: 175
est_num_layers:
  value: 2
est_temperature:
  value: 33
