wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0004954229563720883
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 46
ae_n_kernels_2:
  value: 109
cb_lr:
  value: 0.017069768502006828
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 64
est_d_hidden:
  value: 122
est_dropout:
  value: 0.18889411887967145
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 6
est_kernel_size_4:
  value: 7
est_kernel_size_5:
  value: 7
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 4
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 98
est_n_kernels_1:
  value: 55
est_n_kernels_2:
  value: 44
est_n_kernels_3:
  value: 177
est_n_kernels_4:
  value: 75
est_n_kernels_5:
  value: 84
est_num_layers:
  value: 5
est_temperature:
  value: 31
