wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0010406568447653432
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 56
ae_n_kernels_1:
  value: 37
ae_n_kernels_2:
  value: 193
cb_lr:
  value: 0.029292563860214515
cb_momentum:
  value: 0.8
cb_n_epochs:
  value: 123
est_batch_size:
  value: 256
est_d_hidden:
  value: 253
est_dropout:
  value: 0.16377841780644045
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 176
est_n_kernels_1:
  value: 8
est_n_kernels_2:
  value: 34
est_n_kernels_3:
  value: 110
est_num_layers:
  value: 3
est_temperature:
  value: 31
