wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.02563182692336666
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 25
ae_n_kernels_2:
  value: 88
est_batch_size:
  value: 512
est_d_hidden:
  value: 128
est_dropout:
  value: 0.3744686527776143
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 4
est_lr:
  value: 0.002426428342583171
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_momentum:
  value: 0.9
est_n_basis_kernels:
  value: 90
est_n_epochs:
  value: 1
est_n_kernels_1:
  value: 25
est_n_kernels_2:
  value: 43
est_n_kernels_3:
  value: 88
est_num_layers:
  value: 1
est_temperature:
  value: 33
