wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.000714978147779477
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 20
ae_n_kernels_2:
  value: 168
cb_lr:
  value: 0.015126621903268255
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 244
est_dropout:
  value: 0.2051844213920061
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 5
est_kernel_size_5:
  value: 5
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 242
est_n_kernels_1:
  value: 38
est_n_kernels_2:
  value: 46
est_n_kernels_3:
  value: 200
est_n_kernels_4:
  value: 88
est_n_kernels_5:
  value: 106
est_num_layers:
  value: 5
est_temperature:
  value: 31
