wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.008824966130658906
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 48
ae_n_kernels_2:
  value: 142
est_batch_size:
  value: 64
est_d_hidden:
  value: 128
est_dropout:
  value: 0.3496115646046317
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 2
est_lr:
  value: 0.017774328745528735
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_momentum:
  value: 0.8
est_n_basis_kernels:
  value: 237
est_n_epochs:
  value: 1
est_n_kernels_1:
  value: 19
est_n_kernels_2:
  value: 62
est_n_kernels_3:
  value: 87
est_num_layers:
  value: 2
est_temperature:
  value: 30
