wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.00016055819892023268
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 21
ae_n_kernels_2:
  value: 201
cb_lr:
  value: 0.001477388643713904
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 34
est_dropout:
  value: 0.3162477358474718
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 4
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 28
est_n_kernels_1:
  value: 29
est_n_kernels_2:
  value: 23
est_n_kernels_3:
  value: 105
est_n_kernels_4:
  value: 112
est_n_kernels_5:
  value: 105
est_num_layers:
  value: 2
est_temperature:
  value: 31
