wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.00091158272384341
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 37
ae_n_kernels_2:
  value: 75
cb_lr:
  value: 0.0244411014728526
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 33
est_dropout:
  value: 0.20450162121229096
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 78
est_n_kernels_1:
  value: 21
est_n_kernels_2:
  value: 38
est_n_kernels_3:
  value: 125
est_n_kernels_4:
  value: 115
est_n_kernels_5:
  value: 65
est_num_layers:
  value: 1
est_temperature:
  value: 33
