wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.03555396149845109
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 48
ae_n_kernels_2:
  value: 50
cb_lr:
  value: 0.04155563643199899
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 64
est_d_hidden:
  value: 80
est_dropout:
  value: 0.3388673315436876
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 7
est_kernel_size_4:
  value: 7
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 6
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 36
est_n_kernels_1:
  value: 42
est_n_kernels_2:
  value: 28
est_n_kernels_3:
  value: 92
est_n_kernels_4:
  value: 180
est_n_kernels_5:
  value: 136
est_num_layers:
  value: 5
est_temperature:
  value: 32
