wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.0002177401525503588
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 25
ae_n_kernels_2:
  value: 183
cb_lr:
  value: 0.00450032789115448
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 512
est_d_hidden:
  value: 170
est_dropout:
  value: 0.3381770167998661
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 4
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 6
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 104
est_n_kernels_1:
  value: 21
est_n_kernels_2:
  value: 32
est_n_kernels_3:
  value: 89
est_n_kernels_4:
  value: 78
est_n_kernels_5:
  value: 132
est_num_layers:
  value: 5
est_temperature:
  value: 32
