wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0004803216663480513
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 47
ae_n_kernels_2:
  value: 207
cb_lr:
  value: 0.04807365300996047
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 256
est_d_hidden:
  value: 67
est_dropout:
  value: 0.17597067031602315
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 5
est_kernel_size_4:
  value: 7
est_kernel_size_5:
  value: 7
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 6
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 22
est_n_kernels_1:
  value: 26
est_n_kernels_2:
  value: 46
est_n_kernels_3:
  value: 106
est_n_kernels_4:
  value: 242
est_n_kernels_5:
  value: 68
est_num_layers:
  value: 4
est_temperature:
  value: 31
