wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.00034822271689703655
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 21
ae_n_kernels_2:
  value: 110
cb_lr:
  value: 0.02574591522730134
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 128
est_d_hidden:
  value: 229
est_dropout:
  value: 0.1965282273975914
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 181
est_n_kernels_1:
  value: 29
est_n_kernels_2:
  value: 64
est_n_kernels_3:
  value: 82
est_n_kernels_4:
  value: 80
est_n_kernels_5:
  value: 99
est_num_layers:
  value: 1
est_temperature:
  value: 32
