wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.019932322106998537
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 48
ae_n_kernels_2:
  value: 253
cb_lr:
  value: 0.0011347297037581218
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 256
est_d_hidden:
  value: 200
est_dropout:
  value: 0.19260001418873252
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 5
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 235
est_n_kernels_1:
  value: 19
est_n_kernels_2:
  value: 41
est_n_kernels_3:
  value: 87
est_n_kernels_4:
  value: 98
est_n_kernels_5:
  value: 96
est_num_layers:
  value: 5
est_temperature:
  value: 31
