wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.00025279399569878115
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 3
ae_n_kernels_1:
  value: 27
ae_n_kernels_2:
  value: 36
cb_lr:
  value: 0.003679708731237683
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 128
est_d_hidden:
  value: 162
est_dropout:
  value: 0.1430118977602398
est_kernel_size_1:
  value: 5
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 4
est_maxpooling_3:
  value: 4
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 4
est_n_basis_kernels:
  value: 152
est_n_kernels_1:
  value: 19
est_n_kernels_2:
  value: 36
est_n_kernels_3:
  value: 127
est_n_kernels_4:
  value: 118
est_n_kernels_5:
  value: 110
est_num_layers:
  value: 2
est_temperature:
  value: 33
