wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.00011802903246748418
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 30
ae_n_kernels_2:
  value: 184
cb_lr:
  value: 0.004095920536275129
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 51
est_dropout:
  value: 0.3609147299552863
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 188
est_n_kernels_1:
  value: 27
est_n_kernels_2:
  value: 61
est_n_kernels_3:
  value: 88
est_n_kernels_4:
  value: 66
est_n_kernels_5:
  value: 67
est_num_layers:
  value: 1
est_temperature:
  value: 31
