wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.02105405779632753
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 20
ae_n_kernels_2:
  value: 129
cb_lr:
  value: 0.006360421712703709
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 1
est_batch_size:
  value: 64
est_d_hidden:
  value: 104
est_dropout:
  value: 0.14018838087578545
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 6
est_kernel_size_4:
  value: 6
est_kernel_size_5:
  value: 7
est_maxpooling_1:
  value: 4
est_maxpooling_2:
  value: 5
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 5
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 51
est_n_kernels_1:
  value: 50
est_n_kernels_2:
  value: 57
est_n_kernels_3:
  value: 84
est_n_kernels_4:
  value: 192
est_n_kernels_5:
  value: 157
est_num_layers:
  value: 5
est_temperature:
  value: 31
