wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.0006042822415130494
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 88
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 141
cb_lr:
  value: 0.0013761362917254453
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 103
est_batch_size:
  value: 128
est_d_hidden:
  value: 239
est_dropout:
  value: 0.1654902870759302
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 4
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_n_basis_kernels:
  value: 32
est_n_kernels_1:
  value: 10
est_n_kernels_2:
  value: 52
est_n_kernels_3:
  value: 66
est_num_layers:
  value: 3
est_temperature:
  value: 33
