wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0001594742476260199
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 89
ae_n_kernels_1:
  value: 64
ae_n_kernels_2:
  value: 139
cb_lr:
  value: 0.0347183175455225
cb_momentum:
  value: 0.8
cb_n_epochs:
  value: 135
est_batch_size:
  value: 256
est_d_hidden:
  value: 134
est_dropout:
  value: 0.10936508434794986
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_n_basis_kernels:
  value: 203
est_n_kernels_1:
  value: 12
est_n_kernels_2:
  value: 52
est_n_kernels_3:
  value: 90
est_num_layers:
  value: 1
est_temperature:
  value: 33
