wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.011393712851498957
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 50
ae_n_kernels_2:
  value: 248
cb_lr:
  value: 0.0015260040416375231
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 112
est_dropout:
  value: 0.1955172046267036
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 119
est_n_kernels_1:
  value: 32
est_n_kernels_2:
  value: 42
est_n_kernels_3:
  value: 104
est_n_kernels_4:
  value: 69
est_n_kernels_5:
  value: 92
est_num_layers:
  value: 1
est_temperature:
  value: 32
