wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0006621813321165759
ae_maxpooling_2:
  value: 2
ae_momentum:
  value: 0.6
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 23
ae_n_kernels_2:
  value: 79
cb_lr:
  value: 0.002210210906556817
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 42
est_dropout:
  value: 0.3121800477962603
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 2
est_kernel_size_4:
  value: 3
est_kernel_size_5:
  value: 2
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 2
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 160
est_n_kernels_1:
  value: 12
est_n_kernels_2:
  value: 56
est_n_kernels_3:
  value: 99
est_n_kernels_4:
  value: 90
est_n_kernels_5:
  value: 87
est_num_layers:
  value: 1
est_temperature:
  value: 33
