wandb_version: 1

ae_batch_size:
  value: 64
ae_lr:
  value: 0.0018254726968107329
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 17
ae_n_kernels_2:
  value: 35
cb_lr:
  value: 0.003995039162484501
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 52
est_dropout:
  value: 0.20653139554537195
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 3
est_n_basis_kernels:
  value: 80
est_n_kernels_1:
  value: 20
est_n_kernels_2:
  value: 39
est_n_kernels_3:
  value: 99
est_n_kernels_4:
  value: 77
est_n_kernels_5:
  value: 128
est_num_layers:
  value: 2
est_temperature:
  value: 31
