wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.00502217249051731
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 47
ae_n_kernels_2:
  value: 126
cb_lr:
  value: 0.02210759890057343
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 64
est_d_hidden:
  value: 204
est_dropout:
  value: 0.24145148528816787
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 4
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 34
est_n_kernels_1:
  value: 26
est_n_kernels_2:
  value: 50
est_n_kernels_3:
  value: 127
est_n_kernels_4:
  value: 97
est_n_kernels_5:
  value: 104
est_num_layers:
  value: 2
est_temperature:
  value: 31
