wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.013361021665665171
ae_momentum:
  value: 0.8
ae_n_epochs:
  value: 1
ae_n_kernels_1:
  value: 23
ae_n_kernels_2:
  value: 58
est_batch_size:
  value: 512
est_d_hidden:
  value: 64
est_dropout:
  value: 0.15894739165509802
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_lr:
  value: 0.020651019796461546
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_momentum:
  value: 0.9
est_n_basis_kernels:
  value: 207
est_n_epochs:
  value: 1
est_n_kernels_1:
  value: 23
est_n_kernels_2:
  value: 43
est_n_kernels_3:
  value: 109
est_num_layers:
  value: 3
est_temperature:
  value: 32
