wandb_version: 1

ae_batch_size:
  value: 256
ae_lr:
  value: 0.0001109413140013463
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 42
ae_n_kernels_1:
  value: 61
ae_n_kernels_2:
  value: 232
est_batch_size:
  value: 256
est_d_hidden:
  value: 64
est_dropout:
  value: 0.3702841288901003
est_kernel_size_1:
  value: 2
est_kernel_size_2:
  value: 2
est_kernel_size_3:
  value: 4
est_lr:
  value: 0.0019665631182731232
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 2
est_momentum:
  value: 0.9
est_n_basis_kernels:
  value: 226
est_n_epochs:
  value: 74
est_n_kernels_1:
  value: 12
est_n_kernels_2:
  value: 22
est_n_kernels_3:
  value: 76
est_num_layers:
  value: 3
est_temperature:
  value: 33
