wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.011683514092972363
ae_momentum:
  value: 0.7
ae_n_epochs:
  value: 21
ae_n_kernels_1:
  value: 38
ae_n_kernels_2:
  value: 67
est_batch_size:
  value: 64
est_d_hidden:
  value: 356
est_dropout:
  value: 0.30049181694153837
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 4
est_lr:
  value: 0.007053207210414323
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_momentum:
  value: 0.9
est_n_basis_kernels:
  value: 198
est_n_epochs:
  value: 51
est_n_kernels_1:
  value: 26
est_n_kernels_2:
  value: 60
est_n_kernels_3:
  value: 120
est_num_layers:
  value: 2
est_temperature:
  value: 31
