wandb_version: 1

ae_batch_size:
  value: 512
ae_lr:
  value: 0.0006421077142266654
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.5
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 54
ae_n_kernels_2:
  value: 136
cb_lr:
  value: 0.028446573147423097
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 225
est_dropout:
  value: 0.3967331997888855
est_kernel_size_1:
  value: 4
est_kernel_size_2:
  value: 4
est_kernel_size_3:
  value: 4
est_kernel_size_4:
  value: 4
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 2
est_maxpooling_2:
  value: 3
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 217
est_n_kernels_1:
  value: 15
est_n_kernels_2:
  value: 36
est_n_kernels_3:
  value: 82
est_n_kernels_4:
  value: 115
est_n_kernels_5:
  value: 66
est_num_layers:
  value: 1
est_temperature:
  value: 30
