wandb_version: 1

ae_batch_size:
  value: 128
ae_lr:
  value: 0.02437874440420617
ae_maxpooling_2:
  value: 3
ae_momentum:
  value: 0.9
ae_n_epochs:
  value: 50
ae_n_kernels_1:
  value: 29
ae_n_kernels_2:
  value: 254
cb_lr:
  value: 0.006494292398856628
cb_momentum:
  value: 0.9
cb_n_epochs:
  value: 100
est_batch_size:
  value: 512
est_d_hidden:
  value: 87
est_dropout:
  value: 0.14355293024286447
est_kernel_size_1:
  value: 3
est_kernel_size_2:
  value: 3
est_kernel_size_3:
  value: 3
est_kernel_size_4:
  value: 2
est_kernel_size_5:
  value: 3
est_maxpooling_1:
  value: 3
est_maxpooling_2:
  value: 2
est_maxpooling_3:
  value: 3
est_maxpooling_4:
  value: 3
est_maxpooling_5:
  value: 2
est_n_basis_kernels:
  value: 27
est_n_kernels_1:
  value: 15
est_n_kernels_2:
  value: 18
est_n_kernels_3:
  value: 109
est_n_kernels_4:
  value: 113
est_n_kernels_5:
  value: 114
est_num_layers:
  value: 1
est_temperature:
  value: 33
